### ISSUE TITLE
/table shows edit and translate for ALL languages

### ISSUE THREAD

**Issue by kwikadi** [nickedes/z-baby#10]
This basically 
1) leads to confusion
2) defeats the purpose of the translate columns

The ideal solution would involve using either 
1) The session lang id, or
2) The master language

 and displaying labels/menu/submenu etc only for values associated with that language.

**Comment by nickedes** [comment]
I think we should do translation only when the `session[LanguageID]` is our `MasterLang`.

**Comment by kwikadi** [comment]
But that still won't solve the issue. Because as of right now the user has no way of knowing which language he/she is editing. For eg: https://imgur.com/AVlaPF1 here, in the first case the distinction between hindi and english is apparent, but other entries just look like duplications, or possibly a glitch. And this issue will only increase when the number of languages increases.

**Comment by kwikadi** [comment]
For now, I have coded th pages to only show the master language, and am closing the issue. 
If you feel this solution is less than ideal, you can of course change it to your liking.
