### ISSUE TITLE
SubCat

### ISSUE THREAD

**Issue by nickedes** [nickedes/z-baby#2]
@kwikadi Make checkboxes for SubCategories and after selecting multiple SubCategories, make entry in Table: `IdeaCatSubCat` . Also, make changes for this to `/submit` and `submit.html`.

**Comment by kwikadi** [comment]
on it. You'll probably see a commit for this tomorrow (on windows for now)

**Comment by nickedes** [comment]
:sparkles: :sparkling_heart:
