### ISSUE TITLE
Translation Under admin

### ISSUE THREAD

**Issue by nickedes** [nickedes/z-baby#5]
We need to `translate` for all the tables which `admin`(`Role = 4`) can access.
 For this work under `/table`.

**Comment by kwikadi** [comment]
Is this the one where all the insert queries need to be changed to update?

**Comment by nickedes** [comment]
Yes :dancers:

**Comment by kwikadi** [comment]
I think its fixed now ( I just reused your update methods, which sped up the work considerably).
By the way, I cleaned up the code (/table is ~ half the size it was previously) and commented it too. /super has a similar code bloat. You may want to look into that.
